user
user::user($db, $allOptions)
Constructor $db (object database) the database module $allOptions (null array) an array with empty values. The keys are the extra options.
References $allOptions, $db, initEmpty, isError.
user::initFromDatabaseID($ID)
Initialize the user from the database with key $ID $ID (int) The database ID (error)
References initFromArray, isError.
user::initFromDatabaseLogin()
user::initFromDatabaseEmail()
user::initFromArray($array)
Initializes an user from arrayvalues. $array (mixed array) The required values (keys) are login and email.
References initEmpty, setOption.
Referenced by initFromDatabaseID.
user::addToDatabase()
Adds the user to the database.(error)
References getAllOptions, isError, isInDatabase.
user::removeFromDatabase()
Removes the user from the database;(error)
References isError, isInDatabase.
user::updateToDatabase()
user::updateFromArray()
user::addToGroup()
user::hasRight()
user::getLogin()
user::getEmail()
user::getID()
Referenced by isInDatabase.
user::getAllGroups()
user::getOption($name)
Returns an extra option with name $name (string) The name of the option (string, error)
References getAllOptions.
user::$db
Referenced by user.
user::$allOptions
Referenced by user.
user::$ID
user::$login
user::$email
user::getAllOptions()
Returns an array of all extra options with their values.(mixed array)
Referenced by addToDatabase, getOption, initEmpty, setOption.
user::setOption($name, $value)
Set options $name on $value $name (string) the name of the option $value (mixed) the new value of the options (error)
References getAllOptions.
Referenced by initFromArray.
user::isInDatabase()
Checks if the user is already stored in the database.(bool)
References getID.
Referenced by addToDatabase, removeFromDatabase.
user::initEmpty()
Initialize the user with default values.
References getAllOptions.
Referenced by initFromArray, user.