userManager
userManager::userManager($db)
References $db.
userManager::newUser()
Creates a user object. This is the only good method to create one. Do not use new user (); directly.(object user)
References getAllOptionsForUser, isError.
userManager::loginIsRegistered($login)
Check that an username is already registered. $login (string) the login. (bool). True if user exists, false if not
References isError.
Referenced by addUserToDatabase.
userManager::emailIsRegistered($email)
Check that an email is already registered. $email (string) the email. (bool). True if email exists, false if not
References isError.
Referenced by addUserToDatabase.
userManager::addUserToDatabase($user)
Insert an user into the database. $user (object user) The user. (error). If an error occurs return it.
References emailIsRegistered, isError, loginIsRegistered.
userManager::removeUserFromDatabase($user)
Removes an user from the database. $user (object user) The user to delete. (error). An error if occurs
userManager::addOptionToUser($newOption, $sqlType)
Adds an extra option to the database for the users. $newOption (string) the name of the new option $sqlType (string) the sqltype possible options: Varchar (length)Intenum('a', 'b', 'c')text old user objects don't profit of this. Wait for a restart of the system (reload of the page) to be sure its applied. Bugwhen after adding one, someone ask wich exists the new is added in. if that "asker" want to do something with it on an old user object it can cause weird errors. (error) if one
References getAllOptionsForUser, isError.
userManager::getAllOptionsForUser()
Returns an associative array with values null, and keys the name of the option(null array)
References isError.
Referenced by addOptionToUser, newUser.
userManager::getAllUsers()
userManager::getAllUsersID()
Returns an array of all users that are stored in the database.(int array)
References isError.
userManager::groupExists()
userManager::addGroupToDatabase()
userManager::addOptionToGroup()
userManager::getAllOptionsForGroup()
userManager::removeGroupFromDatabase()
userManager::getAllGroups()
userManager::$db
Referenced by userManager.