databasemanager.functions.php
databaseLoadModule($module)
Loads a database module. Returns the newly created class.module (class) the newly created class.
References $allModules, databaseGetAllModules, databaseModuleExists.
Referenced by MorgOSSuit::setUp, databaseManagerTest::testLoadModule.
databaseGetAllModules($checkReqs=false)
Returns all available modules. If $checkReqs is true it checks of that all requirements (PHP extensions) are installed. $checkReqs (bool) Check that all PHP extensions are installed. array (string) all modules.
References $allModules.
Referenced by databaseLoadModule, databaseModuleExists, databaseManagerTest::testModuleGetAllModules.
databaseModuleExists($module, $checkReqs=false)
Checks if a database module exists. $module (string) the module name to check $checkReqs (bool) Check that the all extensions for that module exists. exists (bool)
References databaseGetAllModules.
Referenced by databaseLoadModule, databaseManagerTest::testModuleExists.
databaseInstallModule()
databaseUnInstallModule()