varia.functions.php
isError($test)
Referenced by userManager::addOptionToUser, user::addToDatabase, userManager::addUserToDatabase, userManager::emailIsRegistered, getAllFields, userManager::getAllOptionsForUser, userManager::getAllUsersID, user::initFromDatabaseID, userManager::loginIsRegistered, userManager::newUser, user::removeFromDatabase, MorgOSSuit::setUp, userManagerTest::testAddUserToDatabase, userManagerTest::testEmpty, user::user.